[phases.build]
cmds = ["./gradlew clean build -x check -x test -Pproduction"]

[start]
cmd = "java -Xmx300m -Xms200m -XX:MaxMetaspaceSize=80m -XX:+UseSerialGC -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xss256k -jar server/build/libs/server.jar"

